DEBUG=True
GROQ_API_KEY=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
ANTHROPIC_API_KEY=sk-
DEFAULT_PROVIDER=Groq
DEFAULT_MODEL=llama3-groq-8b-8192-tool-use-preview
GROQ_MODEL=llama3-groq-8b-8192-tool-use-preview
ANTHROPIC_MODEL=claude-3-5-sonnet-20240620